//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleFSharpEF.Model

    open System
    open System.Collections.Generic
    
    [<CLIMutable>]
    type issues = {
        id : int 
        tracker_id : int 
        project_id : int 
        subject : string 
        description : string 
        due_date : Nullable<System.DateTime> 
        category_id : Nullable<int> 
        status_id : int 
        assigned_to_id : Nullable<int> 
        priority_id : int 
        fixed_version_id : Nullable<int> 
        author_id : int 
        lock_version : int 
        created_on : Nullable<System.DateTime> 
        updated_on : Nullable<System.DateTime> 
        start_date : Nullable<System.DateTime> 
        done_ratio : int 
        estimated_hours : Nullable<float> 
        parent_id : Nullable<int> 
        root_id : Nullable<int> 
        lft : Nullable<int> 
        rgt : Nullable<int> 
        is_private : bool 
        closed_on : Nullable<System.DateTime> 
    }
