//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleFSharpEF.Model

open System
open Microsoft.EntityFrameworkCore

type redmineEntities() = 
    inherit DbContext()

    let CNSTR = "server=localhost;user id=redmine;password=redmine;persistsecurityinfo=True;database=redmine;sslmode=None"

    override x.OnConfiguring( optionsBuilder: DbContextOptionsBuilder ) =
        base.OnConfiguring(optionsBuilder)
        optionsBuilder.UseMySQL(CNSTR) |> ignore

    [<DefaultValue>] val mutable _issues : DbSet<issues>
    member this.issues with get() = this._issues and set v = this._issues <- v
    [<DefaultValue>] val mutable _projects : DbSet<projects>
    member this.projects with get() = this._projects and set v = this._projects <- v


