//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleFSharpEF.Model

    open System
    open System.Collections.Generic
    
    [<CLIMutable>]
    type projects = {
        id : int 
        name : string 
        description : string 
        homepage : string 
        is_public : bool 
        parent_id : Nullable<int> 
        created_on : Nullable<System.DateTime> 
        updated_on : Nullable<System.DateTime> 
        identifier : string 
        status : int 
        lft : Nullable<int> 
        rgt : Nullable<int> 
        inherit_members : bool 
        default_version_id : Nullable<int> 
    }
